#!/bin/bash
# hestia-exim-plain-fix.sh
#
# Purpose:
#   KumoMTA only supports SMTP AUTH PLAIN (it returns "504 5.5.4 AUTH LOGIN
#   not supported" for anything else). HestiaCP's stock Exim relay
#   authenticator uses AUTH LOGIN, so authenticated relay from Hestia to a
#   KumoMTA smart host fails until Exim also offers PLAIN.
#
#   This script ADDS a PLAIN authenticator (smtp_relay_plain) to Hestia's
#   Exim template without removing the existing LOGIN block, then rebuilds
#   and reloads the live Exim config. Exim, as a client, will use whichever
#   mechanism the smart host advertises -- KumoMTA advertises only PLAIN, so
#   it picks smtp_relay_plain; a LOGIN-only smart host still works via the
#   original block.
#
#   It is idempotent (safe to run repeatedly) and self-healing: pair it with
#   the APT hook (99-hestia-exim-plain-fix) so it re-applies automatically
#   after a package update overwrites the template.
#
# Where this runs:
#   On the HestiaCP server (NOT the KumoMTA server). Install to:
#     /usr/local/sbin/hestia-exim-plain-fix.sh   (chmod +x)
#
# Credential format note:
#   PLAIN sends a single string "authzid<NUL>authcid<NUL>password". Exim's
#   plaintext driver converts each '^' to a NUL byte, so the client_send
#   value below (^USER^PASS) yields "<NUL>user<NUL>pass" -- the empty-authzid
#   form KumoMTA expects. If your relay password ever contains '^', ':', '$',
#   '\' or '}', it must be escaped per Exim's string rules.

set -eu

T=/etc/exim4/exim4.conf.template
[ -f "$T" ] || exit 0

# 1) Ensure the PLAIN authenticator block exists in the template.
if ! grep -q '^smtp_relay_plain:' "$T"; then
  awk '
    /^begin authenticators/ && !done {
      print
      print ""
      print "smtp_relay_plain:"
      print "  driver = plaintext"
      print "  public_name = PLAIN"
      print "  hide client_send = ^SMTP_RELAY_USER^SMTP_RELAY_PASS"
      done=1
      next
    }
    { print }
  ' "$T" > "$T.new" && mv "$T.new" "$T"
fi

# 2) Regenerate the live config from the template (Debian/Ubuntu exim4 flow).
#    A plain "reload" alone is NOT enough -- Exim runs the compiled
#    /var/lib/exim4/config.autogenerated, which must be rebuilt first.
if command -v update-exim4.conf >/dev/null 2>&1; then
  update-exim4.conf
fi

# 3) Only reload if the config compiles cleanly, so a future template change
#    can never leave Exim in a broken, non-starting state.
if exim4 -bV >/dev/null 2>&1; then
  systemctl reload exim4 2>/dev/null || systemctl restart exim4 || true
fi
